### ISSUE TITLE
Erro when running 'yarn build'

### ISSUE THREAD

**Issue by MaizerGomes** [samiheikki/javascript-guessing-game#275]
When I run
```
yarn build
```
I get the following error:

```
Using gulpfile ~/Code/webekutiva/guess/gulpfile.js
[14:07:45] Starting 'rename-images'...
[14:07:45] 'rename-images' errored after 1.49 ms
[14:07:45] Error: ENOENT: no such file or directory, rename './dist/static/logos/Adonis.png' -> './dist/static/logos/d7ffd68e-4f91-4492-82e9-cb21b86be2ee.png'
    at Error (native)
    at Object.fs.renameSync (fs.js:811:18)
    at logos.forEach (/home/maizerg/Code/webekutiva/guess/gulpfile.js:21:8)
    at Array.forEach (native)
    at Gulp.<anonymous> (/home/maizerg/Code/webekutiva/guess/gulpfile.js:19:9)
    at module.exports (/home/maizerg/Code/webekutiva/guess/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/maizerg/Code/webekutiva/guess/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/maizerg/Code/webekutiva/guess/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/maizerg/Code/webekutiva/guess/node_modules/orchestrator/index.js:134:8)
    at /home/maizerg/Code/webekutiva/guess/node_modules/gulp/bin/gulp.js:129:20
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! javascript-guessing-game@1.0.0 rename-images: `gulp rename-images`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the javascript-guessing-game@1.0.0 rename-images script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maizerg/.npm/_logs/2017-10-24T12_07_45_569Z-debug.log
error Command failed with exit code 1.
```

**It seems that the task rename-images can't match the name of the logo with the logo file because the name is capitalized while the logo name isn't.**

I belive the fix would be changing
`fs.renameSync('./dist/static/logos/' + logo.name + '.png', './dist/static/logos/' + uuid + '.png');` 
to `fs.renameSync('./dist/static/logos/' + logo.name.toLowerCase() + '.png', './dist/static/logos/' + uuid + '.png');`
**on gulpfile.js**

**Comment by ghost** [comment]
@MaizerGomes would you like to fix it?

**Comment by MaizerGomes** [comment]
@maxv Yes. I've just submitted a pull request.
#280

**Comment by samiheikki** [comment]
What OS are you using? I'm not facing this issue on Mac.

**Comment by MaizerGomes** [comment]
I'm using ElementaryOS Loki, a linux distribution based on Ubuntu 16.04.
